server:
  port: 9001

spring:
  application:
    name: parking-sharing-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://192.168.3.106:3306/parking              # 数据库名称
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://eurakeserver9000.com:9000/eureka
ribbon:
  eureka:
    enabled: true 
feign:
  hystrix:
    enabled: false         
mybatis:
  type-aliases-package: com.parking.common.pojo 
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
